export const actionType = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  CLEAR_INGREDIENTS: 'CLEAR_INGREDIENTS',
  SET_INGREDIENTS: 'SET_INGREDIENTS',
  FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
  PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
  PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
  PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
  PURCHASE_INIT: 'PURCHASE_INIT',
};
